image: gitpod/workspace-full

tasks:
  - init: |
      docker compose -f docker-compose.min.yml build
      docker compose -f docker-compose.min.yml up -d
    command: |
      echo "Waiting for app on port 8080..."

ports:
  - port: 8080
    onOpen: open-preview
